// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: usersv.proto

package userservice

import (
	"context"

	"internal_tools/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GenerateTokenReq  = rpc.GenerateTokenReq
	GenerateTokenRes  = rpc.GenerateTokenRes
	LoginReq          = rpc.LoginReq
	LoginRes          = rpc.LoginRes
	LogoutReq         = rpc.LogoutReq
	LogoutRes         = rpc.LogoutRes
	RefreshTokenReq   = rpc.RefreshTokenReq
	RefreshTokenRes   = rpc.RefreshTokenRes
	RegisterDeviceReq = rpc.RegisterDeviceReq
	RegisterDeviceRes = rpc.RegisterDeviceRes
	SendSmsReq        = rpc.SendSmsReq
	SendSmsRes        = rpc.SendSmsRes
	Token             = rpc.Token
	UserDetail        = rpc.UserDetail
	UserDetailReq     = rpc.UserDetailReq
	UserDetailRes     = rpc.UserDetailRes
	VerifyTokenReq    = rpc.VerifyTokenReq
	VerifyTokenRes    = rpc.VerifyTokenRes

	UserService interface {
		// 用户详情
		UserDetail(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*UserDetailRes, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// 用户详情
func (m *defaultUserService) UserDetail(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*UserDetailRes, error) {
	client := rpc.NewUserServiceClient(m.cli.Conn())
	return client.UserDetail(ctx, in, opts...)
}
