// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: usersv.proto

package server

import (
	"context"

	"github.com/william094/internal-tools/internal/logic/userservice"
	"github.com/william094/internal-tools/internal/svc"
	"github.com/william094/internal-tools/rpc"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// 用户详情
func (s *UserServiceServer) UserDetail(ctx context.Context, in *rpc.UserDetailReq) (*rpc.UserDetailRes, error) {
	l := userservicelogic.NewUserDetailLogic(ctx, s.svcCtx)
	return l.UserDetail(in)
}
