// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: usersv.proto

package server

import (
	"context"

	"github.com/william094/internal-tools/internal/logic/authservice"
	"github.com/william094/internal-tools/internal/svc"
	"github.com/william094/internal-tools/rpc"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

// 设备注册
func (s *AuthServiceServer) RegisterDevice(ctx context.Context, in *rpc.RegisterDeviceReq) (*rpc.RegisterDeviceRes, error) {
	l := authservicelogic.NewRegisterDeviceLogic(ctx, s.svcCtx)
	return l.RegisterDevice(in)
}

// 登录
func (s *AuthServiceServer) Login(ctx context.Context, in *rpc.LoginReq) (*rpc.LoginRes, error) {
	l := authservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 登出
func (s *AuthServiceServer) Logout(ctx context.Context, in *rpc.LogoutReq) (*rpc.LogoutRes, error) {
	l := authservicelogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// 生成token
func (s *AuthServiceServer) GenerateToken(ctx context.Context, in *rpc.GenerateTokenReq) (*rpc.GenerateTokenRes, error) {
	l := authservicelogic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

// Token 校验
func (s *AuthServiceServer) VerifyToken(ctx context.Context, in *rpc.VerifyTokenReq) (*rpc.VerifyTokenRes, error) {
	l := authservicelogic.NewVerifyTokenLogic(ctx, s.svcCtx)
	return l.VerifyToken(in)
}

// Token 刷新
func (s *AuthServiceServer) RefreshToken(ctx context.Context, in *rpc.RefreshTokenReq) (*rpc.RefreshTokenRes, error) {
	l := authservicelogic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

// 短信发送
func (s *AuthServiceServer) SendSms(ctx context.Context, in *rpc.SendSmsReq) (*rpc.SendSmsRes, error) {
	l := authservicelogic.NewSendSmsLogic(ctx, s.svcCtx)
	return l.SendSms(in)
}
