// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: usersv.proto

package authservice

import (
	"context"

	"github.com/william094/internal-tools/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GenerateTokenReq  = rpc.GenerateTokenReq
	GenerateTokenRes  = rpc.GenerateTokenRes
	LoginReq          = rpc.LoginReq
	LoginRes          = rpc.LoginRes
	LogoutReq         = rpc.LogoutReq
	LogoutRes         = rpc.LogoutRes
	RefreshTokenReq   = rpc.RefreshTokenReq
	RefreshTokenRes   = rpc.RefreshTokenRes
	RegisterDeviceReq = rpc.RegisterDeviceReq
	RegisterDeviceRes = rpc.RegisterDeviceRes
	SendSmsReq        = rpc.SendSmsReq
	SendSmsRes        = rpc.SendSmsRes
	Token             = rpc.Token
	UserDetail        = rpc.UserDetail
	UserDetailReq     = rpc.UserDetailReq
	UserDetailRes     = rpc.UserDetailRes
	VerifyTokenReq    = rpc.VerifyTokenReq
	VerifyTokenRes    = rpc.VerifyTokenRes

	AuthService interface {
		// 设备注册
		RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceRes, error)
		// 登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
		// 登出
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutRes, error)
		// 生成token
		GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenRes, error)
		// Token 校验
		VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenRes, error)
		// Token 刷新
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenRes, error)
		// 短信发送
		SendSms(ctx context.Context, in *SendSmsReq, opts ...grpc.CallOption) (*SendSmsRes, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

// 设备注册
func (m *defaultAuthService) RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceRes, error) {
	client := rpc.NewAuthServiceClient(m.cli.Conn())
	return client.RegisterDevice(ctx, in, opts...)
}

// 登录
func (m *defaultAuthService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	client := rpc.NewAuthServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 登出
func (m *defaultAuthService) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutRes, error) {
	client := rpc.NewAuthServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// 生成token
func (m *defaultAuthService) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenRes, error) {
	client := rpc.NewAuthServiceClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}

// Token 校验
func (m *defaultAuthService) VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenRes, error) {
	client := rpc.NewAuthServiceClient(m.cli.Conn())
	return client.VerifyToken(ctx, in, opts...)
}

// Token 刷新
func (m *defaultAuthService) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenRes, error) {
	client := rpc.NewAuthServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// 短信发送
func (m *defaultAuthService) SendSms(ctx context.Context, in *SendSmsReq, opts ...grpc.CallOption) (*SendSmsRes, error) {
	client := rpc.NewAuthServiceClient(m.cli.Conn())
	return client.SendSms(ctx, in, opts...)
}
